export const MEDIAFORGE_SCANFORGE_BROWSER_CAPABILITIES = Object.freeze({
  runtimeTasks: true,
  scanforgePreprocess: true,
  pipeline: true,
  gifProcessing: false,
  decoder: false,
  assets: false,
  browserWorkerEntry: "@gsknnft/mediaforge/browser-worker",
});

export {
  BrowserTaskAdapter,
  executeTaskRequest,
  RuntimeTaskRegistry,
  WorkerPool,
  type RuntimeTaskFailure,
  type RuntimeTaskHandler,
  type RuntimeTaskRequest,
  type RuntimeTaskResponse,
  type RuntimeTaskResult,
  type WorkerPoolStats,
} from "./runtime";

export {
  buildScanForgeProviderRunSheet,
  createMemoryScanForgeStudioProvider,
  planScanForgeArtifactRetention,
  registerScanForgeStudioProviderTasks,
  SCANFORGE_STUDIO_TASKS,
  type ScanForgeArtifact,
  type ScanForgeGenerateInput,
  type ScanForgeGenerateOptions,
  type ScanForgeInputAsset,
  type ScanForgeJobStatus,
  type ScanForgeProviderId,
  type ScanForgeProviderRunSheet,
  type ScanForgeRetentionPlanEntry,
  type ScanForgeStudioJob,
  type ScanForgeStudioProvider,
  type ScanForgeStudioResult,
  type ScanForgeTopologyMetrics,
} from "./scanforgeStudio";

export {
  alignImage,
  alignImageSet,
  generatePreview,
  registerScanForgePreprocessTasks,
  SCANFORGE_PREPROCESS_TASKS,
  splitMatrix,
  type ImageAlignSetTaskInput,
  type ImageAlignSetTaskResult,
  type ImageAlignTaskInput,
  type ImageAlignTaskResult,
  type MatrixSplitCell,
  type MatrixSplitTaskInput,
  type MatrixSplitTaskResult,
  type PreviewGenerateTaskInput,
  type PreviewGenerateTaskResult,
  type SerializableImageData,
} from "./tasks";

export {
  CutEngine,
  NamedClipPlanner,
  PixelMatrixExporter,
  PixelMatrixFileEmitter,
  SpriteAtlasExporter,
  TimelineBuilder,
  VeraShellExporter,
  VideoFrameExtractor,
  createImageSnapStage,
  createImageSnapPreprocess,
  createSnapWithBgRemove,
  type ImageSnapMode,
  type ImageSnapOptions,
  type MediaTimeline,
  type TimelineClip,
  type TimelineFrame,
  type VideoExtractOptions,
} from "./pipeline";
